### ISSUE TITLE
Positive feedback + Possible new issue with instagram maybe suspecting weird account activity

### ISSUE THREAD

**Issue by Orudeon** [ThinkBIG-Company/instantgram-light#2]
Hello! First I'd like to say I'm really impressed by the new version. The UI to confirm what will be downloaded is really clever. It's also way more convenient to download things now with the in-line button than it was when it was opening images in new tabs. I also really appreciate that it's labeling files with the poster, date, time, and image number. I like that I have the option of enabling ad grabs if I really want to.

If you'd like a wishlist, I'd love in-line buttons for next image and previous image on the download interface, however since Firefox bookmarks have a hard limit on characters, I totally understand if it's not feasible. I'd also love the ability to program how it formats filenames, but again I imagine that's a ton of code that wouldn't fit.

Lastly, I have no idea if this is just due to how often I download things in general or because of Instantgram-Light, but today Instagram has asked me twice to verify that it's actually me. It also asked me to put in my password the first time. It _also_ asked me yesterday, so it's probably just because I've also been using WFDownloader to grab entire profiles. They probably have me flagged in general.

Anyway, I figured I'd bring up that last part just in case. It could be my fault (and it probably is) rather than something instantgram is doing.

Thanks so much for what looks like a big overhaul

**Comment by ThinkBIG-Company** [comment]
Hello yes the problem will probably be WFDownloader
because as soon as multiple web requests are made to Instagram at the same time then Instagram recognizes that as a hack attempt and triggers a security mechanism or exactly what you saw.
Instantgram does not make any requests anywhere.

I like your wish list and I'm glad you're using it so much.

I think it is possible to implement your wish list or it is very simple.
The idea instead of a slider, preview buttons to incorporate (Due to the limitation) I find very clever, I would have liked to come up with the idea myself. But for something like this there is the community for support ^^ thanks at this point.

I'm working on a quick implementation depending on the time I have.

Thanks a lot
Sascha

**Comment by ThinkBIG-Company** [comment]
Checkout the new version!
Your wishes have been implemented.
Thank you for your super support!
